name: CI
on:
  push:
    branches:
      - main
  pull_request:
      branches:
        - main

jobs:
  UnitTest:
    name: Unittests on (${{ matrix.lisp }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin/2.4.0, ccl-bin/1.12.2, ecl]
        os: [macos-latest-xlarge]
        target:
        - normal
    steps:
      - uses: actions/checkout@v1
      - name: Set up ${{ matrix.lisp }} via Roswell.
        env:
          LISP: sbcl-bin/2.4.0 # Install rove with the older version of SBCL to pass (ql:quickload :dissect)
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
          ros install ${{ matrix.lisp }}
          ros use ${{ matrix.lisp }}
          ros install rove
      - name: Update $PATH
        run: |
          echo $PATH
          export PATH=/home/runner/.roswell/bin:$PATH
          echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV
      - name: Check $PATH
        run: echo $PATH
      - name: make test
        run: |
          make test